# For more information: https://laravel.com/docs/sail
version: "3"
services:
  vuejs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  laravel.test:
    build:
      context: ./backend/docker/8.1
      dockerfile: Dockerfile
      args:
        WWWGROUP: "1000"
    image: sail-8.1/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:80"
      - "${HMR_PORT:-4000}:4000"
    environment:
      WWWUSER: "1000"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    volumes:
      - "./backend:/var/www/html"
    networks:
      - sail
    depends_on:
      - mysql
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "sail"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "sail"
      MYSQL_USER: "sail"
      MYSQL_PASSWORD: "sail"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "sail-mysql:/var/lib/mysql"
      - "./backend/docker/8.1/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psail"]
      retries: 3
      timeout: 5s
networks:
  sail:
    driver: bridge
volumes:
  sail-mysql:
    driver: local
